# action.yml
name: 'run blender'
description: ''
inputs:
  file-to-load:
    description: 'Filename to render'
    required: false
    default: ''
  
  blender-extra-args:
    description: 'Extra command line arguments for blender execution'
    required: false
    default: ''
  

#outputs:
 # time: # id of output
  #  description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-to-load }} ${{ inputs.blender-extra-args }}
